### PR TITLE
Remove scope dependency

### PR DESCRIPTION
**Pull request by Voles**
This PR is a follow up on #596. It list's the places where we rely on getting / setting the `scope()` of DOM-nodes.

- [x] **`expandAll()` and `collapseAll()` methods of the tree**  
The methods loop recursively through the tree nodes and trigger their `expand()` or `collapse()` methods per node. This can be replaced by listening to these events instead of adding method on the `scope()` object.
- [x] **`dragStart()` function of a node**  
The `dragStart()` method uses the scope of the element to check if a node or the handler is clicked.
- [x] **out of bounds check**  
Check in the [uiTreeNode.js](https://github.com/angular-ui-tree/angular-ui-tree/blob/5fd4194b91c38f0b90423f3c34cd74476afec4cc/source/directives/uiTreeNode.js#L296) file.
- [x] **dragMove() function of a node**  
When moving, the `scope()` of a node element is used to perform checks on the tree root and the element being dragged.

@angular-ui-tree/developers feel free to add more dependencies on the `scope()` method to the list.

### CODE REVIEW

**Comment by StefanCodes** [comment]
@Voles, can I help with this? Last time I played with this branch the drag and drop was still not working. Do you have a plan to fix this on your own or would you like me to do anything?

**Comment by Voles** [comment]
@StefanCodes I'm still working on this. I plan to continue tomorrow. A solution I came up with is to use a service as a map to store node-specific information.

**Comment by Smolations** [comment]
11 days since the last commit? I accidentally broke production yesterday because of this issue. I hope it's not forgotten...

:ping:

**Comment by Voles** [comment]
@Smolations I'm still working on it. The `dragMove` handler is actually more complex than I thought. Getting there, but still need some time to investigate and refactor.

**Comment by Voles** [comment]
@angular-ui-tree/developers  I've finished up the work and the PR is now ready for review. I do have a better understanding now of what's going on in the drag-methods, so I'd like to refactor some of these in the near future.

**Comment by Smolations** [comment]
Home stretch now. You got this, @Voles!  :+1:

**Comment by Voles** [comment]
@StefanCodes are you able to find the time to review this PR? I do not want to merge this without review, as it's quite a chunk of refactoring.

**Comment by StefanCodes** [comment]
Yes, sorry! This completely slipped my mind over the holidays. I will find time to review it today or tomorrow.

**Comment by StefanCodes** [comment]
I was seeing exceptions spring up when dragging a node outside the boundaries of the tree, and also outside the browser window. I fixed those with some guards. I think that also resolves https://github.com/angular-ui-tree/angular-ui-tree/issues/691

**Comment by StefanCodes** [comment]
The code looks great to me. Nice work!
I had to cherry pick bb15c354e45cdc7bfa0fa8b4e0df5dfafa9de9bd to get drag drop working, but after some manual testing I didn't come across any problems. It seems to be working great.

**Comment by lootek** [comment]
+1 for this issue

When we may expect this merged?

**Pull request merged**
