### PR TITLE
Issue #454: fix placeholder width

### PR DESCRIPTION
**Pull request by albi34**

### CODE REVIEW

**Comment by Voles** [comment]
Thanks for this PR @albi34. Can you briefly elaborate the description your fix? Thanks!

**Comment by albi34** [comment]
Hi @Voles , I just added back the line that calculated the width of the placeholder element. It's on the uiTreeNode.js directive, line 135. 
I believe it might have been removed in a past merge (that one if I'm not mistaken: https://github.com/angular-ui-tree/angular-ui-tree/commit/432c73bf9a4db0a34d3e1b8a7ee846e5ce2bfc04#diff-2bd42e539aeba5277f65f2599dfc0338).

**Comment by Voles** [comment]
Great. Is it possible to separate your other changes from this PR to keep things organised? Thanks!

**Comment by albi34** [comment]
@Voles I just synced my fork and updated the pull request with a cleaned-up version. Sorry about the delay, had a crazy week!

**Comment by Voles** [comment]
@albi34 still not able to merge. I've updated the Bower.json file. Maybe it's best to only update the files in the `source/` directory? So without creating the dist files.

Sorry for the trouble, I can't resolve the merge conflict myself as I don't have write access to your repository.

**Comment by Voles** [comment]
@albi34 I've added you're fix to a separate branch so we can release your fix in the next version. Thanks very much for your help!

**Pull request closed without merging**
