### PR TITLE
Fix whitespace at bottom of the page

### PR DESCRIPTION
**Pull request by CalvinFernandez**
Dragging tree passed the bottom of page causes small amount of
whitespace to appear in Chrome

### Strange Bouncing thing
image of broken

### No more bouncing
image of fix

### CODE REVIEW

**Comment by zachlysobey** [comment]
I'm curious, how did you create those fancy *gif*s?

**Comment by CalvinFernandez** [comment]
@zachlysobey; 

1 Quicktime screen cap
2 Uploaded videos to youtube 
3 Converted to .gif with imgur 

 it was kind of an involved process

**Comment by StefanCodes** [comment]
This one works great under Windows: https://screentogif.codeplex.com/

This one is cross platform: https://gyazo.com/
It worked well, but it's cloud-based, so not great if you're creating gifs for confidential work.

Another one for Mac/Win: http://recordit.co/


Thanks, this PR looks like it solves an irritating problem. I will try to take a look soon if Niels doesn't beat me to it.

**Comment by Voles** [comment]
@CalvinFernandez thanks for your work. Can you remove the files under `/dist` from your PR? Otherwise we keep having conflicts when merging other PR's. Thanks!

**Comment by Voles** [comment]
@CalvinFernandez thanks!

**Pull request merged**
