### PR TITLE
Fixed placeholder height calculating

### PR DESCRIPTION
**Pull request by DmitryKrekota**
With this pull request placeholder height calculating without margins, it looks much more beautiful.

### CODE REVIEW

**Comment by Voles** [comment]
@DmitryKrekota thanks for your work! Can you please post a before / after screenshot so we can see what the difference is? Thanks!

**Comment by DmitryKrekota** [comment]
Video recording: https://drive.google.com/file/d/0Bxtv10NlSOEbX19MS1lxZEJja1U/view
As you see content does not jump now.

Start content:
https://drive.google.com/file/d/0Bxtv10NlSOEbbThzWmJJa2hoa3c/view?usp=sharing
After drag action (behavior with my changes):
https://drive.google.com/file/d/0Bxtv10NlSOEbbTY4ckt0X09uMWc/view?usp=sharing
After drag action (current behavior):
https://drive.google.com/file/d/0Bxtv10NlSOEbZk1idTBlaDdzYnc/view?usp=sharing

**Comment by Voles** [comment]
@DmitryKrekota that's indeed much cleaner. Thanks for your help! 💯

**Comment by DmitryKrekota** [comment]
Thanks for merging 😉

**Pull request merged**
