### PR TITLE
Added possibility to cancel Drop

### PR DESCRIPTION
**Pull request by Laurix1983**
*beforeDrop* can return normally or return deferred object to make f.ex confirm dialogs
possible.

**Changes are backwards compatible**

### CODE REVIEW

**Comment by Laurix1983** [comment]
**beforeDrop - possibility to return deferred**
```
		beforeDrop:function(event)
			  				{
			  					
			  			
			  				     var r = $.Deferred();
			  					var sourceModel=event.source.nodeScope.$modelValue;
			  					var destModel=event.dest.nodesScope.$nodeScope.$modelValue;
			  				  
			  					$ngBootbox.confirm('Are you sure you want to move "'+sourceModel.description+'" to "'+destModel.description+'"')
			  				    .then(function() {
			  				        // Drop confirmed
			  					   event.source.nodeScope.$$apply = true;
			  				       r.resolve()
			  				    }, function() {
			  				     // Cancel drop
			  					   event.source.nodeScope.$$apply = false;
			  					  r.resolve()
			  				    
			  				    });
			  					return r;
			  				}
```
** or use in a normal way
```
	beforeDrop:function(event)
			  				{
			  					return true;
			  				}
```

**Comment by bronielsen** [comment]
Hi,
I did not see this pull request before I added my own suggestion in #555 and #556 to get the same effect. 

--Morten

**Comment by Laurix1983** [comment]
Well, we got an acknowledgment that it was really an important issue to handle :)

One question which you can probably answer very fast. What will you return from the *confirmationDialog* function. **boolean** or **promise**?

When this feature get's merged to the actual release I would suggest that it would be **named differently** as one use-case for cancelling the Drop could also be such that we don't show dialog but we want to check after request if server side returns OK or ERROR. Of course then the cancel of drop would happen  after the request returning.

How about **confirmDrop** ?

**Comment by bronielsen** [comment]
It is :)
I answerer your questions in the comments for the pull request #556 to keep things together.

**Comment by Voles** [comment]
Closing, work has been continued in #589

**Pull request closed without merging**
