### PR TITLE
Removed outOfBounds variable

### PR DESCRIPTION
**Pull request by herumtreiber**
Hey,

I found several bugs that are caused by the calculation of outOfBounds not working correctly. The PR #739 was committed to remove the faulty implementation and resolve at least #622 and #763 .

The pull request was unfortunately never merged since it contained merge conflicts. I resolved the conflicts since I really need this fix for our project. I did not test all possible impacts the removing of the variable might have, though.

best,
Sven

### CODE REVIEW

**Comment by Voles** [comment]
@herumtreiber thanks for your work! Can you remove the files in `/dist` from your PR?
What impact does the removal of the outOfBounds calculation have on the behaviour of the component?

**Comment by herumtreiber** [comment]
@Voles no problem. I reverted my commit with the dist files. 

We are using a version with the change in our project at the moment and I couldn't see any negative impacts on the component, yet. I guess that the outOfBounds variable was introduced for performance reasons, but I didn't experience a negative effect on the overall performance either.

We are using the component for drag and drop between multiple trees and also to create hierarchies.

**Comment by herumtreiber** [comment]
Hey @Voles ,

any news about the status of this pull request?

**Comment by Voles** [comment]
@herumtreiber thanks very much for your time and effort! I'll create a new release soon.

**Comment by herumtreiber** [comment]
Thank you! :)

**Comment by Voles** [comment]
@herumtreiber see https://github.com/angular-ui-tree/angular-ui-tree/releases/tag/v2.22.2 🌻

**Comment by herumtreiber** [comment]
Woohoo! That was quick! Thanks a lot! :)

**Pull request merged**
