### PR TITLE
Improves/Fixes data-drag-delay to actually delay dragStart.

### PR DESCRIPTION
**Pull request by foglerek**
Fixes collisions with ng-click on ui-tree-node elements.

Builds on pull request #393, by adding the dragStart callback to the dragStart method.

### CODE REVIEW

**Comment by foglerek** [comment]
Note: d8a6188 was based off PR #393 and had an issue with the callback referencing an undefined variable. I moved the dragStart callback firing to the dragStart() method, after dragInfo has been declared and fetched (as seen in 3b84268).

**Comment by samuv** [comment]
+1

**Comment by msvbg** [comment]
+1

**Comment by Voles** [comment]
Reviewed and tested. Great fix! Please make your PR up-to-date with the `master` branch, so it can be merged.

Thanks again :cake:

**Comment by foglerek** [comment]
Done!
Also fixed all the warnings/errors linter was throwing.

**Comment by Voles** [comment]
Merged, thanks!

**Pull request merged**
