### PR TITLE
Add support for right-to-left trees

### PR DESCRIPTION
**Pull request by dani3l**
Support for RTL trees and determine right level direction.

### CODE REVIEW

**Comment by Voles** [comment]
Thanks for your work, @dani3l! Can you please add some documentation about this functionality. Adding an example to the examples would be even better.

Thanks in advance!

**Comment by dani3l** [comment]
I'm kinda loaded right now but I'll try to get do that on this weekend.
Basically it checks if `<html>` has `dir="rtl"` attribute and determine if you increase/decrease the level according to the document direction. I needed that to an app in Hebrew (can be also used for Arabic and other RTL languages)

**Comment by Voles** [comment]
Ok, thanks @dani3l.

**Comment by Voles** [comment]
@dani3l any updates on this?

**Comment by jacobscarter** [comment]
Addresses issue number #274

**Comment by Voles** [comment]
@dani3l I appreciate your work, but in order to merge this the CI build should succeed. Due to inactivity I've recreated your PR in #822. It would be very handy if you could verify this works as expected.

Thanks again!

**Pull request closed without merging**
