### PR TITLE
When scroll to the parent bottom or top.

### PR DESCRIPTION
**Pull request by yolo2013**
解决当父元素不是body时，拖动到顶部或底部，父元素滚动条不会随着滚动。

The tree's scrollable parent element not the body,Drag a node to the bottom or top side,the parent' scroll can not be trigger.

### CODE REVIEW

**Comment by Voles** [comment]
@JimLiu what do you think about this? I can't really follow the conversation ;-)

**Comment by JimLiu** [comment]
@Voles 
I'll try to merge the code by manual

**Comment by mlenser** [comment]
@JimLiu Any luck with the manual merge?

**Comment by chino23** [comment]
Any news on that? I'd love this feature

**Comment by Voles** [comment]
This PR looks quite old and honestly I can't make much sense of the conversation :no_mouth: 
@yolo2013 can you reopen a new PR based on the latest release if this functionality is still wanted?

**Pull request closed without merging**
