### PR TITLE
Table example E2E-tests (broken)

### PR DESCRIPTION
**Pull request by zachlysobey**

### CODE REVIEW

**Comment by zachlysobey** [comment]
This builds on #681 but adds a broken unit test for drag and drop.The expectations all pass actually, but I discovered that the state I'm testing against is *wrong*. I test that the node *before* dragging is node #1, then after dragging that the new first node is node #2.  The idea was to test that they were swapped, but it looks like node #1 is just disappearing and not being added back to the tree by the time the expectation runs.

Looks like this may be true of the similar *basic-example* test too. (`should allow moving a node below another node`).

This is very much a bummer, as I thought I had *that* working at least. Maybe its just a timing thing and I need to add some sort of sleep/wait into the test? In any case, I'm tapped out for the night. I welcome an extra set of eyes if anyone has time.

**Comment by Voles** [comment]
Actually, the table examples were broken ;-) So testing the example pages does help us during the development! @zachlysobey if you rebase your PR onto master, the tests should pass.

**Comment by zachlysobey** [comment]
@Voles I wish that were the case, but I fear that the tests I've written so far which use drag+drop are fundamentally flawed.

I was aware of the broken examples, and was trying to write a test to confirm the fix and prevent further regressions. In doing so, I discovered the issue mentioned in [my comment above](https://github.com/angular-ui-tree/angular-ui-tree/pull/682#issuecomment-166475048)

**Comment by Voles** [comment]
@zachlysobey after fiddling with it, moving the element manually seems to work. 

```
var nodeToDrag = basicExamplePage.getNodeAtPosition(2, 1).getHandle();

      browser.actions()
        .mouseMove(nodeToDrag, {x: 0, y: 0})
        .mouseDown()
        .mouseMove(nodeToDrag, {x: 0, y: 175})
        .mouseMove(nodeToDrag, {x: 0, y: 0})
        .mouseUp()
        .perform();
```

Can you confirm this works for you? If it does, we can write a helper for it.

**Comment by zachlysobey** [comment]
I'll take a look this evening. Thanks for taking a stab! That last revelation was a bit of a downer for me :(

**Comment by zachlysobey** [comment]
Sorry, that took me a bit longer to get around to than I thought. But I took a stab at those changes, and wasn't able to get it to work.

Check out my new branch:
https://github.com/zachlysobey/angular-ui-tree/tree/e2e-still-broken

Specifically this commit:
https://github.com/zachlysobey/angular-ui-tree/commit/d91fc2fb5ecf5decd09150f446dadd33cef5fca3

Doesn't seem to work for me though

**Comment by Voles** [comment]
@zachlysobey after a couple of hours I've managed to find another solution based on your branch.

First of all, specify 'chrome' as browser in the Protractor configuration file.

**Changes for `e2e/basic-example.js`**
```
it('should allow moving a node below another node', function () {

      var nodeToDrag = basicExamplePage.getNodeAtPosition(2, 1);

      nodeToDrag
        .getText()
        .then(function (text) {
          expect(text).toEqual('node2.1');
        });

      // make sure the element to drag is inside the browser's viewport
      browser.wait(browser.executeScript('arguments[0].scrollIntoView();', basicExamplePage.getNodeAtPosition(2).getHandle().getWebElement()));

      browser.actions()
        .mouseMove(nodeToDrag.getHandle(), {x: 0, y: 0})
        .mouseDown()
        .mouseMove(nodeToDrag.getHandle(), {x: 0, y: 0}) // Initial move to trigger drag start
        .mouseMove(nodeToDrag.getHandle(), {x: 2, y: 70})
        .mouseUp()
        .perform();

      basicExamplePage
        .getNodeAtPosition(2, 1)
        .getText()
        .then(function (text) {
          expect(text).toEqual('node2.2');
        });
    });
```
**Changes for `e2e/table-example.js`**
```
it('should allow moving a node below another node', function () {

      tableExamplePage
        .getNodeAtPosition(1)
        .getText()
        .then(function (nodeTextBeforeDrag) {
          expect(nodeTextBeforeDrag).toBe('node 1');
        });

      // make sure the element to drag is inside the browser's viewport
      browser.wait(browser.executeScript('arguments[0].scrollIntoView();', tableExamplePage.getNodeAtPosition(1).getHandle().getWebElement()));

      var nodeToDrag = tableExamplePage.getNodeAtPosition(1);

      browser.actions()
        .mouseMove(nodeToDrag.getHandle(), {x: 0, y: 0})
        .mouseDown()
        .mouseMove(nodeToDrag.getHandle(), {x: 0, y: 0}) // Initial move to trigger drag start
        .mouseMove(nodeToDrag.getHandle(), {x: 25, y: 100})
        .mouseUp()
        .perform();

      tableExamplePage
        .getNodeAtPosition(1)
        .getText()
        .then(function (nodeTextAfterDrag) {
          expect(nodeTextAfterDrag).toBe('node 2');
        });
    });
```

Note: I'm using Node v4.2.4

**Comment by zachlysobey** [comment]
@Voles awesome, thanks for taking the time to dig into that. Not sure I'll get a chance today, but hopefully will be able to roll this all in at some point in the next week or so.

**Comment by zachlysobey** [comment]
Ok, I'm working on integrating these ideas into the page-objects for a bit of a nicer api.

So... do you know what the deal is with the Firefox vs Chrome thing? I didn't investigate any further than noticing that they failed in FFox....

**Comment by Voles** [comment]
@zachlysobey thanks for the heads up!

I've managed to get the tests working locally with Chrome & Firefox. However, the test using D&D still fails on Firefox when running with Travis. See #696

Do you have any ideas?

**Comment by Voles** [comment]
Looks like I've figured it out :-) `browser.actions().dragAndDrop()` does work both locally and when running with Travis. At least for Firefox, locally this fails for Chrome.

I suggest we merge the update to Node v4.2.4 for now, with the working E2E-tests on Firefox. Later, we can further investigate what's going wrong on Chrome.

@zachlysobey how do you think about this?

**Comment by zachlysobey** [comment]
@Voles uhhhh... well I definitely think you should upgrade to node 4 asap as long as travis won't report any failures. I can take another stab after that. I think we have enough information now at least to get these tests up/running and actually testing something useful, but I'd rather not spin my wheels too much on the older platform.

**Comment by Voles** [comment]
@zachlysobey guess we can continue with this now v2.14.0 and v2.15.0 are released. Let me know if you need any help with this!

**Comment by zachlysobey** [comment]
Got a busy couple weeks coming up, but I'm excited to make this work. I'll let you know when I get into it again.

**Comment by jacobscarter** [comment]
@Voles is this still relevant? Can we close it?

**Comment by Voles** [comment]
@zachlysobey are you able to put in some more time so we can finish up this PR? I think the work you've done is really valuable for the project, so it would be nice if we can merge this one.

**Comment by zachlysobey** [comment]
@Niels,

I can't say that its likely I'll be able to work on this in the near
future. I have a new job outside the angular ecosystem, and it demands a
lot more of my time, so its very difficult to motivate myself to do *any*
OSS work, much less angular stuff.
That said, I'll keep subscribed to the issues/repo -- and maybe in the
future I'll get a chance to do some more.

Zach@Lysobey.com
(203) 984-4048

**Comment by jacobscarter** [comment]
@Voles so I guess the question is do we keep this PR open or close it :/

**Comment by Voles** [comment]
@zachlysobey thanks for letting us know!
@jacobscarter I'd like to keep this PR open for a bit so I can maybe extract some logic into a new PR.

**Comment by jacobscarter** [comment]
@Voles sounds good to me

**Comment by zachlysobey** [comment]
Its been over a year with no movement on this. I'm closing it, but feel free to re-open

**Pull request closed without merging**
