### PR TITLE
Expand-on-hover event not calling the toggle callback function

### PR DESCRIPTION
**Pull request by FernandoMueller**
add function callback toggle

### CODE REVIEW

**Comment by jmaupin82** [comment]
Just wanted to comment and say I would find this valuable as well!

**Comment by Voles** [comment]
@FernandoMueller @jmaupin82 shouldn't calling the `toggle()` callback be on the line before? Now it's using the return value of that function for the timeout value.

**Comment by Agshlee** [comment]
@Voles @FernandoMueller @jmaupin82 Any updates on this change? Currently working on a project where we would really like to have this functionality available. Anything I can do to help in getting this to the master in a timely fashion?

Thanks!

**Comment by Voles** [comment]
@Agshlee see my latest comment. Does this fix work for you if you put the `done()` callback on the line before?

**Comment by Agshlee** [comment]
@Voles Not entirely. Calling scope.toggle() switches the toggled state on the scope of the dragged item, but that's not needed. The scope it passes to the toggled function is also that of the dragged item, where I would expect the scope of the target item (unless this is explicitly not the intended behavior).

I believe the code should be something along the following lines:

```
if (scope.expandOnHover === true || (angular.isNumber(scope.expandOnHover) && scope.expandOnHover === 0)) {
    targetNode.collapsed = false;
    scope.$treeScope.$callbacks.toggle(false, targetNode);
} else if (scope.expandOnHover !== false && angular.isNumber(scope.expandOnHover) && scope.expandOnHover > 0) {
    //Triggering expansion.
    if (angular.isUndefined(scope.expandTimeoutOn)) {
        scope.expandTimeoutOn = targetNode.$id;

        scope.$callbacks.expandTimeoutStart();
        scope.expandTimeout = $timeout(function()
        {
                scope.$callbacks.expandTimeoutEnd();
                targetNode.collapsed = false;
                scope.$treeScope.$callbacks.toggle(false, targetNode);
        }, scope.expandOnHover);
    }
}
```

Note that this code should also be added to the "no toggle delay"

**Comment by Voles** [comment]
@Agshlee thanks very much for your explanation.

If this PR is incorrect and you need the solution, could you please open a new PR with the changes needed? I believe the fix in this PR is invalid and so we need a new proposal. Thanks in advance! 🌷

**Comment by Agshlee** [comment]
@Voles Yeah I'll do that. Before I do, however, could you help me understand something? 

The toggle callback (but also the other callbacks) are always called on the source tree, rather than the target tree (assuming a situation where the target is a different tree). For some events this might make sense, but for example for dropped and toggle (and probably others) it does not. Do you know why it was developed this way? 

If there is no specific reason for doing it this way, I would argue that some (or all) of the events could trigger on the target->treeScope->callbacks. This means the callbacks are called correctly for multiple trees, but still work for single trees as well (as the target obviously resolved to the one tree).

**Comment by Voles** [comment]
Closing since this is resolved with #899

**Pull request closed without merging**
