### PR TITLE
added rtl support

### PR DESCRIPTION
**Pull request by Adam-Goldman7**
It might be better to refactor the '$uiTreeHelper' factory as a provider, so it could be configured on the fly. Maybe I'll do it soon.

### CODE REVIEW

**Comment by Adam-Goldman7** [comment]
Added dynamic support to change direction on the fly, as well as a way to set the default to 'rtl' or 'ltr'

**Comment by Voles** [comment]
It would be good to add unit tests for this behaviour. I've fixed the build in an upcoming PR #341.

**Comment by Voles** [comment]
The [build failed](https://travis-ci.org/angular-ui-tree/angular-ui-tree/builds/47962684) because of a JSHint issue, can you please fix this?

**Comment by Adam-Goldman7** [comment]
Fixed.
I've tested it live along with some of my customers and teammates. Works good.

I don't have time to add unit tests at the moment.

Have you gone over the code?
and questions / comments?

**Comment by Voles** [comment]
@Adam-Goldman7 great work, thanks! +1 for adding documentation as well :+1:

**Comment by Adam-Goldman7** [comment]
Sure!
What's code without documentation ;)

**Comment by ashraffayad** [comment]
@Adam-Goldman7 I'm trying to use the rtl feature but it doesn't work. I tried to alter the tree config as shown in your commit, also, I tried to change the tree direction dynamically using the attributes. both didn't work. 
I checked the source code and I didn't find your commit there!

**Comment by Adam-Goldman7** [comment]
yes I know

The latest update broke it :(
ᐧ

**Comment by pashaie** [comment]
@Adam-Goldman7 any update for `rtl` support?
as @ashraffayad said, your committed changes aren't in source code any more.
thanks.

**Comment by Adam-Goldman7** [comment]
After I added rtl support, there was a version update that broke it, and I
haven't modified
the rtl support for the new update, so it's gone.

PS.
I thought I posted this info already (my bad!)

**Comment by Voles** [comment]
@Adam-Goldman7, @pashaie sorry for the inconvenience with the version update. The revert took place [here](https://github.com/angular-ui-tree/angular-ui-tree/commit/800dd0a43ce105d6301cd42038c1a28dbe3cd21e).

We have a trusted release flow by now, so if any of you would create a new PR with rtl-support, we can add it to an upcoming release. The source code with changes needed should all be within this PR I believe (is that correct, @Adam-Goldman7?).

**Comment by Adam-Goldman7** [comment]
too many changes there for me to follow :/

It's not hard tho if I remember correctly i just inverted the x axis if
either:
1.  an rtl flag was passed in the configuration through the provider in
.config
2. an attribute with dir="rtl" was added to the directive in the html

I got too much on me hands right now,
maybe will do it someday :)

**Pull request merged**
