### PR TITLE
Rename API attribute for toggling the empty placeholder

### PR DESCRIPTION
**Pull request by Voles**
It seems that the functionality for toggling the empty placeholder is working correctly, but the documentation is incorrect. Because the property name is emptyPlaceHolderEnabled, the attribute should be `empty-place-holder-enabled`.

However, as `empty-placeholder-enabled` makes more sense, the API has been updated to reflect this.

Big thanks to @adambowen

### CODE REVIEW

**Comment by Voles** [comment]
@adambowen I'm not sure about your suggestion:

> The code uses typeof attrs.emptyPlaceHolderEnabled == "boolean", but this is a DOM attribute and therefore has the type "string".

When I test the scenario by passing a scope variable (eg. `<div empty-placeholder-enabled="enablePlaceholder"></div>`), this works as expected. Same goes for passing the boolean directly `<div empty-placeholder-enabled="false"></div>`.

**Comment by Voles** [comment]
@adambowen can you review?

**Comment by adambowen** [comment]
In our environment (with the browser/angular versions in #448) I definitely needed typeof `attrs.emptyPlaceHolderEnabled == "string"` in order for the attribute to have any effect. I'm bothered that you have found `empty-placeholder-enabled="enablePlaceholder"` works because I haven't spotted anything in the code that would cause `empty-placeholder-enabled` to be evaluated as a JavaScript expression (either a two way data binding, scope expression binding or `$parse`/`$eval` call). Without evaluation I would expect Angular to pass it through the attrs object as a string.

**Comment by adambowen** [comment]
@Voles Ok I see now that `$watch` is being used to evaluate the attribute, which I missed before. I'm not sure why our app is having issues. I've found a couple of bugs which I've added test cases for and fixed, I'll open a PR (as soon as I get used to git's workflow - we use mercurial at work :)).

**Comment by adambowen** [comment]
I've opened #452 to address a couple of issues I found. I also noticed the configuration attribute for the placeholder class is still called `placeHolderClass`. For consistency, it should probably be called `placeholderClass`, but as with renaming the attribute this would be a breaking change for anyone using it so I've held off changing it for now.

**Comment by Voles** [comment]
I've renamed `placeHolderClass` to `placeholderClass`. It makes sense to do this now, while we're renaming the API anyway. I'll merge #452 after this one.

@adambowen thanks for your feedback & help! :cake:

**Pull request merged**
