### PR TITLE
Issue #511 - $parentNodeScope is null and can not access $id

### PR DESCRIPTION
**Pull request by joechimo**
Encountered an ongoing issue after a recent merge into master to fix an edge case.  The following was the error:

```javascript
TypeError: Cannot read property '$id' of null
    at Object.dragInfo.apply (http://127.0.0.1:8080/js/vendor.js:31906:85)
    at http://127.0.0.1:8080/js/vendor.js:31595:30
    at Scope.$get.Scope.$eval (http://127.0.0.1:8080/js/vendor.js:14466:28)
    at Scope.$get.Scope.$apply (http://127.0.0.1:8080/js/vendor.js:14565:23)
    at link.dragEnd (http://127.0.0.1:8080/js/vendor.js:31594:36)
    at HTMLDocument.link.dragEndEvent (http://127.0.0.1:8080/js/vendor.js:31636:15)
    at HTMLDocument.eventHandler (http://127.0.0.1:8080/js/vendor.js:3032:21) undefined
```

### CODE REVIEW

**Comment by Voles** [comment]
Thanks for your work! Merged.

**Comment by marsanla** [comment]
Is this merge, updated in Bower?

**Comment by Voles** [comment]
Yes v2.7.0 is just released!

**Comment by marsanla** [comment]
thanks!! :)

**Pull request merged**
