### PR TITLE
#372 Expand subtree on drag over after 500ms.

### PR DESCRIPTION
**Pull request by rd-dev-ukraine**
This expands subtree on draging when hovering standing mouse cursor over tree node due 500ms (hardcoded)

### CODE REVIEW

**Comment by Voles** [comment]
@rd-dev-ukraine great contribution! Can you bring your PR in sync with the `master` branch?

**Comment by vgekhman** [comment]
Niels, do you know when these changes will be included into the released version?  At this time v 2.5.0 does not appear to have this.

**Comment by Jacquelin** [comment]
@Voles : Hi, any news about these changes ? 

thx

**Comment by Voles** [comment]
Due to inactivity I've recreated this PR. There's still some work to be done. See #539.

**Comment by Jacquelin** [comment]
@Voles Thank you very much for your reply !!

**Pull request closed without merging**
