### PR TITLE
improved/fixed drag-delay option

### PR DESCRIPTION
**Pull request by xat**
With this PR the `dragStartEvent` function gets called after waiting the time specified within the drag-delay option. I also got rid of some state variables.

### CODE REVIEW

**Comment by samuv** [comment]
This improvement is great, but you delete the call of dragStart on dragMove:
```javascript
scope.$apply(function() {
  scope.$callbacks.dragStart(dragInfo.eventArgs(elements, pos));
});
```

**Comment by foglerek** [comment]
Hi,

Currently having issues with this as ng-clicks on a ui-tree-handle child element trigger a dragged event on the element (despite having drag-delay set to a non-zero value). Is this fix going to get merged in?

**Comment by samuv** [comment]
@foglerek For me this fix the problem that I have with ng-click but the pull request is incomplete and broke callback methods

**Comment by foglerek** [comment]
@samuv do you mind submitting a fixed pull request? I ended up using your proposed solution and it seems to be working without breaking callback methods.

**Comment by Voles** [comment]
Please refer to this PR number when creating a new PR. Reviews are welcome!

**Comment by foglerek** [comment]
@voles done.
@samuv I went ahead and submitted a new pull request, hope you don't mind. Also moved the dragStart callback to the dragStart() method instead of dragMove().

**Comment by samuv** [comment]
@foglerek You did it good, my reference was incorrect where I added the dragStart to dragMove, i never updated the pull request but in my fork I fixed the problem moving the callback in the correct method like you did. Anyway i saw the pull request. Great job.

**Comment by Voles** [comment]
I've reviewed PR #444 of @foglerek, closing this one as it's a duplicate.
@xat thanks for looking into this! :cake:

**Pull request closed without merging**
