### PR TITLE
Fix horizontal movement detection

### PR DESCRIPTION
**Pull request by jacobscarter**
Fixes issue #562

### CODE REVIEW

**Comment by Voles** [comment]
LGTM. I'm curious what exactly is a horizontal tree? I can't imagine how it would be used.

**Comment by jacobscarter** [comment]
@voles I have no idea. Just left over code from something that existed once upon a time. Good riddance I say :)

**Comment by Voles** [comment]
@jacobscarter aha, great :-) I suggest we'll merge and release #825 before merging this one. Can you review #825?

**Comment by jacobscarter** [comment]
Yeah tomorrow morning. It's 12:17am where I'm at now. If you can give the green light for merge on this one I'll review merge and release #825 and then merge and release this one. Assuming you give the green light.

**Comment by Voles** [comment]
@jacobscarter ✅ this PR can be merged. You can merge #825 if you're ok with it.

**Comment by StefanCodes** [comment]
@Voles - I recall seeing a reference to it on the demo pages when JimLiu's account still owned the project. I never saw it after the move to the angular-ui-tree account, but I see a reference to it in this old commit: https://github.com/angular-ui-tree/angular-ui-tree/commit/0b052fff25d370a04b1f8416d88a433e5569389a

I assumed in the original 2.18 PR merge that all the code removed was related to that feature (but there was, as I quickly discovered, more code removed than that).

I don't think we need to do anything about it specifically, other than keep it in mind that the code base is several years old and might some cruft code that isn't doing anything useful anymore.

**Comment by Voles** [comment]
@StefanCodes you're right. Thanks for providing the details on this!

**Pull request merged**
