### PR TITLE
Fix compatibility with debuginfo disabled

### LINKED ISSUE #521: Disabling debugInfo results in inability to re-order nodes.
When I disable Angular's debug info using the steps in [this Egghead tutorial](https://egghead.io/lessons/angularjs-new-in-angular-1-3-performance-boost-with-debuginfoenabled) in order to gain a performance boost, I lose the ability to drag and drop items. No information is logged in the console.

The following configuration option is what breaks the re-ordering:

```
module.config([ '$compileProvider', ($compileProvider) {
 $compileProvider.debugInfoEnabled(false);
}]);
```

Is `ui-tree` relying on attributes added by angular's debug info?

### PR DESCRIPTION
**Pull request by Voles**
Closes #521 and #425.
Contains the fix as created by https://github.com/gamejolt/angular-ui-tree

### CODE REVIEW

**Comment by Voles** [comment]
@angular-ui-tree/developers please review

**Comment by wwsno** [comment]
The line `outOfBounds = !(targetElm.data('_scope').$type);` is missing a check if the element has _scope as data.

**Comment by StefanCodes** [comment]
At a glance this looks like a great solution, but I will take a closer look and do some testing this evening. Thanks @Voles!

**Comment by StefanCodes** [comment]
@Voles I'm seeing errors on my end when I test this in basic_example.

It's throwing errors on line 305 of uiTreeNode.js (https://github.com/angular-ui-tree/angular-ui-tree/pull/596/files#diff-2bd42e539aeba5277f65f2599dfc0338R305) - `Uncaught TypeError: Cannot read property '$type' of undefined`. 

targetElm doesn't have a _scope data property at that point - looks like the scope is added to every element (li.angular-ui-tree-node), but the targetElm is an li.angular-ui-tree-placeholder.

I tried a naive fix by adding `placeElm.data('_scope', scope);` to line 145 (immediately after the placeholder element is created), but this seemed to make the drag behaviour start acting very strange (and still surfaced the same exceptions, though not as many).

Can you reproduce this?

**Comment by mikehuebner** [comment]
Any update on this issue?

**Comment by evanpaschke** [comment]
+1

**Comment by Voles** [comment]
I've been looking into this for a couple of days / evenings now, but the usage of `scope()` is too widespread to solve this at once.

My solution to use data-attributes as alternative for `scope()` works at some places, but not everywhere. Eg. in [uiTreeNode.js line 336](https://github.com/angular-ui-tree/angular-ui-tree/blob/f0ea6da152f91ab4b6998b07f25aded9e3860d00/source/directives/uiTreeNode.js#L336) it's easy to replace `.scope()` with `.data('_scope')` (= getting the scope values from the data attribute). But at line 343, the `$treeScope` is expected on the retrieved scope value. I don't want to store the whole `$treeScope` in every data-attribute.

It's no good to get the `scope()` in so many places and even rely on a certain nested parent structure of it ([L343](https://github.com/angular-ui-tree/angular-ui-tree/blob/f0ea6da152f91ab4b6998b07f25aded9e3860d00/source/directives/uiTreeNode.js#L343)). This makes the directives / controllers too intertwined and extremely difficult to test. It causes duplication and  is not well designed IMHO.

The only clean way to solve this is by refactoring the tree directives and controllers to not get certain elements and their `$scope`. But this definitely means API changes and a lot of rewriting.

Anyone else's thoughts about this?

/cc @angular-ui-tree/developers

**Comment by mikehuebner** [comment]
Just to chime in and discuss this a bit, I would have to look at the code base more in depth but I think I'm seeing where you're connecting everything here. As the `.scope()` is basically bound to those elements, no? I was expecting this to be class name issue as it couldn't find any of the class names that were given (which is what I assume `.scope()` does). But I agree, if you start over using `scope` it gets messy, very quickly, so it would be a bad idea to even touch that. I'll keep working on ideas as I get free time to help you out, just going to review the code base tonight and I'll start poking around at different ideas. Thanks for the update!

**Comment by StefanCodes** [comment]
I agree @Voles, this is too widespread a problem to have a simple solution. A large scale refactoring is necessary. Like you said, storing the $treeScope in every data attribute would be a mess, and would undermine the performance benefits of disabling debug mode in the first place.

I see 3 usages of `scope()` - and assume that if those could be replaced, we'd have no further issues with debug mode compatibility?

The first is at the beginning of the `dragMove` handler, and is only used to check if we're dragging over a node or handle, and returns if certain conditions aren't met. That seems like something that can be implemented a different way without too much difficulty - it's only using `scope.$type` and one check for a tree handle scope.

The second is also in `dragMove` and used to determine if the mouse is currently out of bounds.

The third is difficult, since it uses `scope()` to get a node's scope and do a lot of manipulation based on different scope properties.

I'm happy to assist with this issue as well but don't have any good ideas on how to solve this.

**Comment by Voles** [comment]
Closed, work has been continued in #648

**Pull request closed without merging**
