### PR TITLE
Cannot read property 'childNodes' of undefined

### PR DESCRIPTION
**Pull request by thecatontheflat**
Extra check for recursive call of the countSubTreeDepth

screenshot 2015-11-15 20 57 19

### CODE REVIEW

**Comment by Voles** [comment]
Thanks! :+1:

**Comment by thecatontheflat** [comment]
No problem! Don't forget to update the minified version ;)

**Comment by brianfeister** [comment]
@Voles. I'm running into this, can we merge this PR?

**Comment by ConnectedReasoning** [comment]
This is happening to me even with the file change

**Comment by carolinagc** [comment]
For some reason, this fix is not present in v2.17 but you can do a patch but applying the fix described in https://github.com/angular-ui-tree/angular-ui-tree/commit/7df850e38b80ca9bc6201319df37ae2755d1471d

**Comment by carolinagc** [comment]
Hey @jacobscarter , can you check this issue? 
There is commit that was supposed to be merged, this one:
https://github.com/angular-ui-tree/angular-ui-tree/commit/7df850e38b80ca9bc6201319df37ae2755d1471d

but also in current version it does not appear
https://github.com/angular-ui-tree/angular-ui-tree/blob/master/dist/angular-ui-tree.js#L168

**Comment by jacobscarter** [comment]
Hey @carolinagc we just recently got our merging and releasing process documented so hopefully this wont happen again! I'll fix it now

**Comment by jacobscarter** [comment]
Version 2.21.1 now has the fix

**Comment by carolinagc** [comment]
@jacobscarter great!!! thanks!! :+1:

**Pull request merged**
