### PR TITLE
Expand subtree on drag over after 500ms

### PR DESCRIPTION
**Pull request by Voles**
WIP

Todo:
- add example on the website
- add docs

Reference: #386

### CODE REVIEW

**Comment by luciano-masuero** [comment]
This did not work for me :(

**Comment by Voles** [comment]
@luciano-masuero can you clarify what exactly didn't work for you?

**Comment by luciano-masuero** [comment]
@Voles sorry for the delay. I try this and the expand on drag did not work after the 500ms... Has this merged into master? So I can retest

**Comment by Voles** [comment]
Deprecated. Please open a new PR if this functionality is desired.

**Pull request closed without merging**
