### PR TITLE
Setup JSCS configuration

### PR DESCRIPTION
**Pull request by Voles**
Add JSCS validation to enforce a predefined code style.

### CODE REVIEW

**Comment by Voles** [comment]
Ready for review.
/cc @honkskillet, @chino23, @meriturva, @kotmatpockuh, @enkodellc, @kether667

**Comment by kether667** [comment]
a lot of files changes, i couldn't see any changes in functionality just code styles - which is good since it's the intention here, tests passed so this one looks good, unless you want us to look at something particular?

**Comment by kotmatpockuh** [comment]
will be great to see "updated demo" )

**Comment by chino23** [comment]
looks beautiful now, nice!

**Comment by Voles** [comment]
Thanks all, merged. Let's push things forward again! :balloon:

**Comment by enkodellc** [comment]
@Voles isn't it time to update the package version??? 
Also it doesn't look like any of my clone changes are in the master branch. What happened?

**Comment by Voles** [comment]
@enkodellc is it common to bump the version for every change? Curious to hear you opinion about this one.

Your changes to the clone functionality have been merged before and are published with the v2.3.0 release. See https://github.com/angular-ui-tree/angular-ui-tree/commit/dd277cbd3349eb82bc4887b5d59d12c859828742?diff=unified

**Comment by enkodellc** [comment]
http://stackoverflow.com/questions/3826580/what-rules-does-software-version-numbering-follow
http://en.wikipedia.org/wiki/Software_versioning

In my opinion it is not common to bump for every change but definitely for feature changes, breaking changes, and some bug fixes. We know that version 2.1.5 was broken so if any fixes were made I would suggest a patch version bump. In our case since we fixed bugs and added features the 2.3 minor version is appropriate. For your JSCS update it should have at least moved to 2.1.6 patch. 

Strange I don't see version 2.3 in the branches? I see 2.3 in releases. Maybe I am missing something. I would suggest merging 2.3 into master as it fixed several issues and added features that are commonly requested. 

In addition as @kotmatpockuh suggested we should have an updated demo as well.

**Comment by Voles** [comment]
I don't see why we would backport the JSCS improvements. These don't add anything to previous releases, except for code style. Correct me if I'm wrong.

We do not have any branches related to the versions. Everything is on `master` and when a new version is released, this is nothing more than a tag.

I'm very much open for suggestions about the development flow!

You're right that the demo's should be updated, but that's out of scope for this PR.

**Pull request merged**
