### PR TITLE
Prevents child node scope with no children to be counted in depth.

### PR DESCRIPTION
**Pull request by Whyves**
When specifying maxDepth and using a template in ng-include to generate the tree nodes, a template is created for empty children. This causes the logic in maxSubDepth to include the depth of non-existent children thus going over the max depth limit and preventing node moves even when they were valid. I have added a test  for this.

### CODE REVIEW

**Comment by Voles** [comment]
@Whyves nice improvement! Can you bring your PR up-to-date with the `master` branch?

**Comment by Whyves** [comment]
Tried to rebase but you changed the name attribute in package.json to "AngularJS UI Tree" and that prevents me from running "npm install" it complains about "AngularJS UI Tree" to be invalid. Putting "-" instead of spaces fix the problem. May I suggest that you rename  "AngularJS UI Tree" to "angular-ui-tree" which seems more standard. I am under Ubuntu. Once this is fixed, I will rebase my changes.

**Comment by Voles** [comment]
Fixed, sorry for the inconvenience...

**Comment by Whyves** [comment]
There you go, PR up-to-date. Sorry for the multiple commits. I had a few issues with jscs :-)

**Comment by Voles** [comment]
Thanks for this, @Whyves!

**Pull request merged**
