### PR TITLE
#611 Put drag element to the $rootElement instead of the body

### LINKED ISSUE #611: Put drag element to the $rootElement instead of 'body'
It seems it's an only correct way since host angular app can be limited to an element which is neither `html` nor `body`. Putting temp drag element outside of app's root element breaks encapsulation. 

It's also a common practice to apply styles to app's root element and its descendants, instead of the whole document. That's easy nowadays with CSS preprocessing tools like Less or Sass with their `@import` directives. Thus a temp drag element outside of app's root element does not get correct styles.

Well, it's all about encapsulation.

PR is coming.

### PR DESCRIPTION
**Pull request by dangoodman**
Fixes #611

### CODE REVIEW

**Comment by dangoodman** [comment]
I'm not sure, did the travis build failed due to my changes?

**Comment by StefanCodes** [comment]
I'm able to run the e2e tests locally and they all pass, but the Travis logs show that Protractor failing with an exception. I don't see how your changes could result in this error.

```
[15:21:00] Starting 'test:e2e'...
[15:21:00] Starting 'protractor'...
[15:21:00] Finished 'test:e2e' after 82 ms
/home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Object #<Object> has no method 'parse'
    at Function.ConfigParser.resolveFilePatterns (/home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/lib/configParser.js:102:29)
    at new TaskScheduler (/home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/lib/taskScheduler.js:31:31)
    at /home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/lib/launcher.js:180:21
    at _fulfilled (/home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/home/travis/build/angular-ui-tree/angular-ui-tree/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
/home/travis/build/angular-ui-tree/angular-ui-tree/tasks/protractor.js:11
        throw error;
              ^
Error: protractor exited with code 8
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

@Voles did you encounter anything like this when you were setting up the e2e tests?

**Comment by dangoodman** [comment]
@StefanCodes, thank you for response. Sadly @Voles did not pleased us with his comment.

Well, now travis build goes successfully. I've just forced it to re-run and it went ok. Not sure what's changed. What I can say for sure is that the commit did not changed.

For now, is there any reason to not merge the commit?

**Comment by Voles** [comment]
Sorry for the late reply. The PR looks good, merged!

**Comment by dangoodman** [comment]
Thanks!

**Comment by Voles** [comment]
@dangoodman are you interested in helping us with further development of the component? :-)

**Comment by dangoodman** [comment]
Yep. I'm going to do a couple of drag-n-drop UX improvements. Hopefully you'll accept them. Or do you mean something else?

**Comment by Voles** [comment]
No, that would be perfect! Looking forward :+1:

**Pull request merged**
